// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import { Component, OnInit, ElementRef } from '@angular/core';
import { GranularityEnum, LineChartConfig } from 'lfx-insights';

@Component({
  selector: 'lfx-code-review-engagement',
  templateUrl: './code-review-engagement.component.html',
  styleUrls: ['./code-review-engagement.component.scss']
})
export class CodeReviewEngagementComponent implements OnInit {
  public title = 'CODE REVIEW ENGAGEMENT';
  public description = 'Trends in the participation of contributors who are engaged in pull request review related activities.';
  public activeCardId: any;
  public cards = [
    {
      id: 0,
      title: 'Pull Request Participants',
      value: '15',
      changeFromPrevious: -7,
      // TODO: this text needs to be autogenerated by 2 values : [3, 92]
      insightsDescription: '3% of project contributors are b{responsible for 92%} i{0} of all pull request activity compared to the previous time period.'
    },
    {
      id: 1,
      title: 'Pull Requests Reviewed',
      value: '3219',
      changeFromPrevious: 22,
      insightsDescription: `Pull request reviews are b{up 22%} i{0} compared to the previous time period.`
    },
    {
      id: 2,
      title: 'Review Comments Per Pull Request',
      value: '6',
      changeFromPrevious: 21,
      insightsDescription: `Comments per pull request are b{up 4%} i{1} compared to the previous time period.`
    },
    {
      id: 3,
      title: 'Code Reviews',
      value: '27',
      changeFromPrevious: 21,
      insightsDescription: `Code reviews are b{up 16%} i{1} compared to the previous time period.`
    }
  ];

  public configLineReviewed: LineChartConfig = {
    showLegend: true,
    yAxisName: 'Pull Requests Reviewed',
    series: [
      {
        field: 'value',
        name: 'Pull Requests Reviewed',
        color: '#46b6c7',
        bullets: true
      }
    ],
    xAxis: {
      field: 'date',
      axisType: 'date',
      granularity: GranularityEnum.week
    },
    type: 'smooth'
  };
  public configPerPullRequest: LineChartConfig = {
    showLegend: true,
    yAxisName: 'Review Comments',
    series: [
      {
        field: 'value',
        name: 'Review Comments',
        color: '#0039b8',
        bullets: true
      }
    ],
    xAxis: {
      field: 'date',
      axisType: 'date',
      granularity: GranularityEnum.week
    },
    type: 'smooth'
  };
  public configCodeReviews: LineChartConfig = {
    showLegend: true,
    yAxisName: 'Code Reviews',
    series: [
      {
        field: 'value',
        name: 'Code Reviews',
        color: '#bd6bff',
        bullets: true
      }
    ],
    xAxis: {
      field: 'date',
      axisType: 'date',
      granularity: GranularityEnum.week
    },
    type: 'smooth'
  };
  public constructor(public elementRef: ElementRef) {}
  public ngOnInit(): void {
    this.activeCardId = this.cards[0].id;
  }

  public updateActiveCard(cardId: any) {
    this.activeCardId = cardId;
  }
}
