# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

---
name: Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  add-reviewers:
    if: github.event.pull_request.draft == false
    name: Add Reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: '.github/workflows/config/reviewers.yml'
