---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Snyk Scan NPM Dependencies

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  pull_request:
    branches:
      - main

jobs:
  snyk-scan-npm-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
        id: snyk
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          npm config set '//npm.pkg.github.com/:_authToken' "${{ secrets.LF_ENGINEERING_NPM_AUTH_TOKEN }}"
      - name: Yarn Version
        run: yarn --version
      - name: Yarn Install
        run: yarn install
      - name: Snyk version
        run: echo "${{ steps.snyk.outputs.version }}"
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Scan for NPM Vulnerabilities
        run: |
          snyk test --org=${{ secrets.SNYK_ORG }} --file=package.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
      - name: Monitor for NPM Vulnerabilities
        run: snyk monitor --org=${{ secrets.SNYK_ORG }} --severity-threshold=high --file=package.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
